---
# Deploy Docker Container For PostgreSQL
- name: Deploy Docker Container PostgreSQL
  docker_container:
    name: "{{ container_name }}"
    image: "{{ container_image }}"
    restart_policy: always
    state: started
    ports: "{{ container_ports }}"
    env: "{{ container_env }}"
